In [2]:
import pandas as pd
import numpy as np

In [22]:
abs = pd.read_csv(r'E:\papx\end_to_end_ml\nb_pr\bvl_live_tracker1\scraper\data\bap_stock_data.csv')

In [28]:
abs

,currentPrice,previousClose,open,dayLow,dayHigh,bid,ask,volume,averageVolume,dividendYield,...,grossMargins,ebitdaMargins,operatingMargins,financialCurrency,returnOnAssets,returnOnEquity,bookValue,priceToBook,symbol,timestamp
0,191.119995,186.16,186.9,186.63,191.48,190.63,190.91,58010,288413,4.99,...,0.0,0.0,0.44671,PEN,0.02272,0.16518,432.381,0.442018,BAP,2025-04-01 10:28:36.233211
1,190.699997,186.16,186.9,186.63,191.48,190.90,192.06,60875,288413,4.99,...,0.0,0.0,0.44671,PEN,0.02272,0.16518,432.381,0.441046,BAP,2025-04-01 10:33:35.108170
2,190.904999,186.16,186.9,186.63,191.48,190.97,192.06,62131,288413,4.99,...,0.0,0.0,0.44671,PEN,0.02272,0.16518,432.381,0.441520,BAP,2025-04-01 10:38:35.172243
3,190.919998,186.16,186.9,186.63,191.48,190.97,192.07,63279,288413,4.99,...,0.0,0.0,0.44671,PEN,0.02272,0.16518,432.381,0.441555,BAP,2025-04-01 10:43:35.142809
4,190.962494,186.16,186.9,186.63,191.48,190.11,191.31,64035,288413,4.99,...,0.0,0.0,0.44671,PEN,0.02272,0.16518,432.381,0.441653,BAP,2025-04-01 10:48:35.346107
5,191.154999,186.16,186.9,186.63,191.48,190.50,191.31,65726,288413,4.99,...,0.0,0.0,0.44671,PEN,0.02272,0.16518,432.381,0.442099,BAP,2025-04-01 10:53:35.567021
6,191.195007,186.16,186.9,186.63,191.48,190.50,191.34,66508,288413,4.99,...,0.0,0.0,0.44671,PEN,0.02272,0.16518,432.381,0.442191,BAP,2025-04-01 10:58:35.103766
7,191.195007,186.16,186.9,186.63,191.48,190.50,191.34,67763,288413,4.99,...,0.0,0.0,0.44671,PEN,0.02272,0.16518,432.381,0.442191,BAP,2025-04-01 11:03:35.102135
8,191.494995,186.16,186.9,186.63,191.53,190.50,191.20,70262,288413,4.99,...,0.0,0.0,0.44671,PEN,0.02272,0.16518,432.381,0.442885,BAP,2025-04-01 11:08:35.424776
9,191.860001,186.16,186.9,186.63,192.10,190.90,191.49,72182,288413,4.99,...,0.0,0.0,0.44671,PEN,0.02272,0.16518,432.381,0.443729,BAP,2025-04-01 11:13:35.185634
10,192.240005,186.16,186.9,186.63,192.24,190.90,191.58,73425,288413,4.99,...,0.0,0.0,0.44671,PEN,0.02272,0.16518,432.381,0.444608,BAP,2025-04-01 11:18:35.355886

In [24]:
abd = pd.read_csv(r'E:\papx\end_to_end_ml\nb_pr\bvl_live_tracker1\scraper\data\brk_b_stock_data.csv')

In [27]:
abd

,currentPrice,previousClose,open,dayLow,dayHigh,bid,ask,volume,averageVolume,dividendYield,...,grossMargins,ebitdaMargins,operatingMargins,financialCurrency,returnOnAssets,returnOnEquity,bookValue,priceToBook,symbol,timestamp
0,533.179993,532.58,531.88,527.5001,536.41,532.59,532.99,1369478,4461705,NaN,...,0.30621,0.34082,0.25908,USD,0.06393,0.14653,451367.2,0.001181,BRK-B,2025-04-01 10:28:38.862460
1,532.869995,532.58,531.88,527.5001,536.41,533.75,534.00,1427483,4461705,NaN,...,0.30621,0.34082,0.25908,USD,0.06393,0.14653,451367.2,0.001181,BRK-B,2025-04-01 10:33:37.472204
2,533.349976,532.58,531.88,527.5001,536.41,533.51,533.99,1472890,4461705,NaN,...,0.30621,0.34082,0.25908,USD,0.06393,0.14653,451367.2,0.001182,BRK-B,2025-04-01 10:38:37.089308
3,532.890015,532.58,531.88,527.5001,536.41,532.90,533.42,1508793,4461705,NaN,...,0.30621,0.34082,0.25908,USD,0.06393,0.14653,451367.2,0.001181,BRK-B,2025-04-01 10:43:37.257390
4,532.940002,532.58,531.88,527.5001,536.41,532.56,532.84,1544170,4461705,NaN,...,0.30621,0.34082,0.25908,USD,0.06393,0.14653,451367.2,0.001181,BRK-B,2025-04-01 10:48:37.199729
5,532.999878,532.58,531.88,527.5001,536.41,532.87,533.44,1590398,4461705,NaN,...,0.30621,0.34082,0.25908,USD,0.06393,0.14653,451367.2,0.001181,BRK-B,2025-04-01 10:53:37.388710
6,533.424988,532.58,531.88,527.5001,536.41,532.66,532.87,1613571,4461705,NaN,...,0.30621,0.34082,0.25908,USD,0.06393,0.14653,451367.2,0.001182,BRK-B,2025-04-01 10:58:36.956573
7,534.284973,532.58,531.88,527.5001,536.41,532.80,533.22,1642921,4461705,NaN,...,0.30621,0.34082,0.25908,USD,0.06393,0.14653,451367.2,0.001184,BRK-B,2025-04-01 11:03:37.161371
8,534.299988,532.58,531.88,527.5001,536.41,532.46,533.00,1675962,4461705,NaN,...,0.30621,0.34082,0.25908,USD,0.06393,0.14653,451367.2,0.001184,BRK-B,2025-04-01 11:08:37.257365
9,534.450012,532.58,531.88,527.5001,536.41,533.24,533.60,1711257,4461705,NaN,...,0.30621,0.34082,0.25908,USD,0.06393,0.14653,451367.2,0.001184,BRK-B,2025-04-01 11:13:37.077427
10,535.219910,532.58,531.88,527.5001,536.41,534.14,534.50,1748949,4461705,NaN,...,0.30621,0.34082,0.25908,USD,0.06393,0.14653,451367.2,0.001186,BRK-B,2025-04-01 11:18:37.453647

In [25]:
abf = pd.read_csv(r'E:\papx\end_to_end_ml\nb_pr\bvl_live_tracker1\scraper\data\ilf_stock_data.csv')

In [26]:
abf

,currentPrice,previousClose,open,dayLow,dayHigh,bid,ask,volume,averageVolume,dividendYield,...,grossMargins,ebitdaMargins,operatingMargins,financialCurrency,returnOnAssets,returnOnEquity,bookValue,priceToBook,symbol,timestamp
0,23.860001,23.55,23.57,23.57,23.8900,23.86,23.87,109179,1308555,6.95,...,NaN,NaN,NaN,USD,NaN,NaN,26.571,0.897972,ILF,2025-04-01 10:28:37.437727
1,23.844999,23.55,23.57,23.57,23.8900,23.88,23.90,116224,1308555,6.95,...,NaN,NaN,NaN,USD,NaN,NaN,26.571,0.897407,ILF,2025-04-01 10:33:36.306812
2,23.875000,23.55,23.57,23.57,23.8900,23.87,23.89,129266,1308555,6.95,...,NaN,NaN,NaN,USD,NaN,NaN,26.571,0.898536,ILF,2025-04-01 10:38:36.099231
3,23.875000,23.55,23.57,23.57,23.8950,23.85,23.85,133317,1308555,6.95,...,NaN,NaN,NaN,USD,NaN,NaN,26.571,0.898536,ILF,2025-04-01 10:43:36.326496
4,23.885000,23.55,23.57,23.57,23.8950,23.84,23.85,136316,1308555,6.95,...,NaN,NaN,NaN,USD,NaN,NaN,26.571,0.898912,ILF,2025-04-01 10:48:36.283123
5,23.920200,23.55,23.57,23.57,23.9202,23.88,23.89,145967,1308555,6.95,...,NaN,NaN,NaN,USD,NaN,NaN,26.571,0.900237,ILF,2025-04-01 10:53:36.484703
6,23.905001,23.55,23.57,23.57,23.9202,23.87,23.88,157588,1308555,6.95,...,NaN,NaN,NaN,USD,NaN,NaN,26.571,0.899665,ILF,2025-04-01 10:58:36.039576
7,23.930000,23.55,23.57,23.57,23.9300,23.89,23.90,162871,1308555,6.95,...,NaN,NaN,NaN,USD,NaN,NaN,26.571,0.900606,ILF,2025-04-01 11:03:36.020416
8,23.945000,23.55,23.57,23.57,23.9650,23.89,23.91,193960,1308555,6.95,...,NaN,NaN,NaN,USD,NaN,NaN,26.571,0.901170,ILF,2025-04-01 11:08:36.360793
9,23.934999,23.55,23.57,23.57,23.9650,23.90,23.91,194398,1308555,6.95,...,NaN,NaN,NaN,USD,NaN,NaN,26.571,0.900794,ILF,2025-04-01 11:13:36.158923
10,23.952600,23.55,23.57,23.57,23.9700,23.91,23.93,197306,1308555,6.95,...,NaN,NaN,NaN,USD,NaN,NaN,26.571,0.901457,ILF,2025-04-01 11:18:36.292879

In [29]:
abf.columns

Index(['currentPrice', 'previousClose', 'open', 'dayLow', 'dayHigh', 'bid',
       'ask', 'volume', 'averageVolume', 'dividendYield', 'earningsGrowth',
       'revenueGrowth', 'grossMargins', 'ebitdaMargins', 'operatingMargins',
       'financialCurrency', 'returnOnAssets', 'returnOnEquity', 'bookValue',
       'priceToBook', 'symbol', 'timestamp'],
      dtype='object')

In [33]:
# Si solo quieres trabajar con el archivo ilf_stock_data.csv
df = pd.read_csv('scraper/data/ilf_stock_data.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'scraper/data/ilf_stock_data.csv'